# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2442e16a85ce1a4c7a64732a47292ab0676d214b2fc043809450d5d8f6549eae3be1b14bc90006761675a09900f1c91ee84a173cc1e1e1ca203d77d33d645ab9

test:
  secret_key_base: 28d51e954ad82696790e8dc7107e445799e708eedd034af4e388fad491c0b5affd1911de3680fb21f3d967dc2a98a19de824c8230d9b417e52f9dfaf86b76624

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
